(SELECT NAME AS RESULTS
 FROM USERS U JOIN MOVIERATING M
                   ON U.USER_ID=M.USER_ID
 GROUP BY M.USER_ID
 ORDER BY COUNT(M.USER_ID) DESC,U.NAME LIMIT 1)
UNION ALL
(SELECT TITLE AS RESULTS
 FROM MOVIES MV JOIN MOVIERATING M
                     ON MV.MOVIE_ID=M.MOVIE_ID
 WHERE M.CREATED_AT LIKE '2020-02-%'
 GROUP BY M.MOVIE_ID
 ORDER BY AVG(M.RATING) DESC,MV.TITLE LIMIT 1)